version: "3.8"

services:

  db:
    image: postgres:15
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: on-failure
    env_file: .env
    depends_on:
      - db
    ports:
      - "5000:5000"

volumes:
  pgdata:
